"""Initial schema setup

Revision ID: ca962f4261fb
Revises: None
Create Date: 2026-08-26 20:22:50.815486+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import pgvector.sqlalchemy
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ca962f4261fb'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # Ensure pgvector extension is enabled in PostgreSQL before creating vector columns
    op.execute("CREATE EXTENSION IF NOT EXISTS vector;")

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('programs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('university_name', sa.String(length=200), nullable=False),
    sa.Column('program_name', sa.String(length=300), nullable=False),
    sa.Column('degree_level', sa.String(length=20), nullable=True),
    sa.Column('field', sa.String(length=100), nullable=True),
    sa.Column('country', sa.String(length=50), nullable=True),
    sa.Column('min_gpa', sa.Float(), nullable=True),
    sa.Column('min_ielts', sa.Float(), nullable=True),
    sa.Column('min_toefl', sa.Integer(), nullable=True),
    sa.Column('tuition_fee', sa.Float(), nullable=True),
    sa.Column('currency', sa.String(length=10), nullable=True),
    sa.Column('deadline', sa.Date(), nullable=True),
    sa.Column('requirements_text', sa.Text(), nullable=True),
    sa.Column('source_url', sa.Text(), nullable=True),
    sa.Column('confidence_score', sa.Float(), nullable=True),
    sa.Column('verification_status', sa.String(length=50), nullable=True),
    sa.Column('verified_by', sa.String(length=100), nullable=True),
    sa.Column('last_updated', sa.Date(), server_default=sa.text('CURRENT_DATE'), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_programs_id'), 'programs', ['id'], unique=False)
    op.create_table('scholarships',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=300), nullable=False),
    sa.Column('provider', sa.String(length=200), nullable=True),
    sa.Column('country', sa.String(length=50), nullable=True),
    sa.Column('degree_level', sa.String(length=20), nullable=True),
    sa.Column('min_gpa', sa.Float(), nullable=True),
    sa.Column('min_ielts', sa.Float(), nullable=True),
    sa.Column('eligibility_text', sa.Text(), nullable=True),
    sa.Column('amount', sa.Text(), nullable=True),
    sa.Column('deadline', sa.Date(), nullable=True),
    sa.Column('source_url', sa.Text(), nullable=True),
    sa.Column('last_updated', sa.Date(), server_default=sa.text('CURRENT_DATE'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_scholarships_id'), 'scholarships', ['id'], unique=False)
    op.create_table('students',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('hashed_password', sa.String(length=255), nullable=True),
    sa.Column('gpa', sa.Float(), nullable=True),
    sa.Column('ielts', sa.Float(), nullable=True),
    sa.Column('toefl', sa.Integer(), nullable=True),
    sa.Column('degree_level', sa.String(length=20), nullable=True),
    sa.Column('field_of_study', sa.String(length=100), nullable=True),
    sa.Column('country', sa.String(length=50), nullable=True),
    sa.Column('research_experience', sa.Boolean(), nullable=True),
    sa.Column('projects', sa.Text(), nullable=True),
    sa.Column('budget', sa.String(length=50), nullable=True),
    sa.Column('goals', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_students_email'), 'students', ['email'], unique=True)
    op.create_index(op.f('ix_students_id'), 'students', ['id'], unique=False)
    op.create_table('university_documents',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('university_id', sa.Integer(), nullable=True),
    sa.Column('program_id', sa.Integer(), nullable=True),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=1536), nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_university_documents_id'), 'university_documents', ['id'], unique=False)
    op.create_index(op.f('ix_university_documents_program_id'), 'university_documents', ['program_id'], unique=False)
    op.create_index(op.f('ix_university_documents_university_id'), 'university_documents', ['university_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_university_documents_university_id'), table_name='university_documents')
    op.drop_index(op.f('ix_university_documents_program_id'), table_name='university_documents')
    op.drop_index(op.f('ix_university_documents_id'), table_name='university_documents')
    op.drop_table('university_documents')
    op.drop_index(op.f('ix_students_id'), table_name='students')
    op.drop_index(op.f('ix_students_email'), table_name='students')
    op.drop_table('students')
    op.drop_index(op.f('ix_scholarships_id'), table_name='scholarships')
    op.drop_table('scholarships')
    op.drop_index(op.f('ix_programs_id'), table_name='programs')
    op.drop_table('programs')
    # ### end Alembic commands ###
